### ISSUE TITLE
End Portal Wipes Coffins

### ISSUE THREAD

**Issue by CarterHidalgo** [Now-this-is-crazy/Coffins#3]
This is an edge case but it was the first death I had after installing this mod (I was tired of my stuff despawning and the coffin block looked much better than the traditional gravestone) so I figured you might want to know. I entered the end portal too fast and died because I kept my momentum and hit the obsidian platform too hard. No problem; I saw the coffin spawn in on the death screen. However, because the obsidian platform is wiped every time you enter the end, when I re-entered the end portal it removed the coffin. As far as I know there would be no way to access the coffin if you were to die on the obsidian platform in the end because when you respawn in the Overworld and re-enter, it would delete the coffin block along with all the items inside. Like I said, its an edge case and I understand if you aren't interested in fixing it, I just wanted you to be aware it existed. Cheers. :)

**Comment by Powercyphe** [comment]
Sorry for the late response, but I will fix this in a week, as im currently on vacation

**Comment by Powercyphe** [comment]
Fixed this to act similar to chests, that it drops the items.
